### ISSUE TITLE
Simplify README in multiple docs in '/docs' folder

### ISSUE THREAD

**Issue by krishnadurai** [Path-Check/safeplaces-backend#192]
All docs are a part of the main README folder.

We could look to separate them into the following files:

1. Dev setup
2. Auth and DB setup
3. Production setup
4. Data access

cc @aiyan @sublet

**Comment by MarshallMcCoy** [comment]
@krishnadurai I'm already working on cleaning up our documentation. Will take your above suggestion into consideration.

**Comment by krishnadurai** [comment]
Thanks @MarshallMcCoy

**Comment by MarshallMcCoy** [comment]
Going to go ahead an close this since its being tracked here...https://pathcheck.atlassian.net/browse/PLACES-451
