### ISSUE TITLE
POST /safe_paths response:  "publish_date_utc" should be "publish_date"

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-backend#32]
https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/Safe-Places-Server.md#publish

**Comment by altoplano** [comment]
I'm late to the party here, but had comented in slack that the "_utc" makes it much clearer that the time is UTC based, not local time, nor server time, nor user time, ...
Time handling is an easy thing to get wrong, the original API spec had the "_utc" in it, perhaps to help prevent some of these problems arising.
