### ISSUE TITLE
Readme doesn't cover updates to pg_hba.conf

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-backend#37]
In addition to the steps in the README, I needed to edit pg_hba.conf in the postgres (12) configuration to add a line under IPv4 local connections for my docker container, namely:

host    all             all             172.17.0.2/32           md5

**Comment by sherifkozman** [comment]
This why its simpler to use the docker-compose implementation in dev environment as it takes care of the networking part.
README can be updated to cate for those who are running with a separate Postgres local deployment

**Comment by krishnadurai** [comment]
Sure @AdamLeonSmith, I'll update the instructions in the README.
