### ISSUE TITLE
Unaggregated data should be encrypted at rest using a salt

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-backend#42]
I.e. data that is uploaded from the redaction tool.  This will affect performance, but only to the degree of the time taken to save/load a single patient's data.

**Comment by krishnadurai** [comment]
@AdamLeonSmith Is it enough to encrypt the redacted trails' coordinate and time data?

**Comment by AdamLeonSmith** [comment]
Yes.

**Comment by krishnadurai** [comment]
@elHoudini9 PTAL a look at this issue. We may need to implement this in NestJS app version as well.

**Comment by krishnadurai** [comment]
@AdamLeonSmith looks like Path-Check/covid-safe-paths#806 would take care of encrypting co-ordinate data by sending them in as geo-hashes instead of co-ordinates.
Related docs: https://docs.google.com/document/d/1mQYh6iQ0zxOwPjHdNFXxmQJ9vgchIq5JxP0on1StvtE

**Comment by AdamLeonSmith** [comment]
@krishnadurai I just discussed with Diarmid.  Intent is that while a patient is undiagnosed we store in hashed form (for EN), and plain text (for CT), then at the point of disclosure to a HA the plain text version is sent to Safe Places, but hashed before publishing.

We may end up geohashing before sending to Safe Places, but that is still sensitive when considered in it's unaggregated form.

So I think this issue stands...

**Comment by krishnadurai** [comment]
@AdamLeonSmith Thanks for clarifying this.
